version: "2.4"

services:
  pihole:
    image: ovelayos/pihole-wd-ex4100:2026.04.1-ex4100-r4
    container_name: pihole-ex4100-diag
    hostname: pihole-ex4100-diag
    restart: "no"

    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "8081:80/tcp"
      - "8443:443/tcp"

    environment:
      TZ: Europe/Andorra
      FTLCONF_webserver_api_password: CAMBIA_ESTA_PASSWORD
      FTLCONF_dns_listeningMode: ALL

    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
      - CHOWN

    security_opt:
      - seccomp:unconfined

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
